Repository TYPO3-Headless/headless, pull requests merged in 2021-11, with the labels that each got.

#366 Task/add backend module t3 11 php74
  Classes/Controller/JsonViewController.php
  Classes/Dto/JsonViewDemand.php
  Classes/Dto/JsonViewDemandInterface.php
  Classes/Service/BackendTsfeService.php
  Classes/Service/BackendTsfeServiceInterface.php
  Classes/Service/JsonViewConfigurationService.php
  Classes/Service/JsonViewConfigurationServiceInterface.php
  Classes/Service/PaginationService.php
  Classes/Service/Parser/DefaultJsonParser.php
  Classes/Service/Parser/JsonParserInterface.php
  Classes/Service/Parser/PageJsonParser.php
  Classes/Utility/JsonViewMenusUtility.php
  Configuration/TypoScript/Configuration/Module.typoscript
  Configuration/Yaml/HeadlessModule.yml
  Documentation/Configuration/Index.rst
  Documentation/Images/Configuration/JsonViewModule-example.png
  Documentation/Images/Configuration/JsonViewModule-extconf.png
  Documentation/Images/Configuration/JsonViewModule-settings.png
  Documentation/Images/Configuration/JsonViewModule.png
  README.md
  Resources/Private/Backend/Layouts/Default.html
  Resources/Private/Backend/Partials/JsonCodeBlockElement.html
  Resources/Private/Backend/Partials/Settings.html
  Resources/Private/Backend/Partials/Settings/Menu.html
  Resources/Private/Backend/Partials/Tabs.html
  Resources/Private/Backend/Templates/Main.html
  Resources/Private/Language/locallang_be.xlf
  Resources/Private/Language/locallang_mod.xlf
  Resources/Public/Css/JsonView.css
  Resources/Public/Css/prism.css
  Resources/Public/Icons/module-jsonview.svg
  Resources/Public/JavaScript/JsonView.js
  Resources/Public/JavaScript/prism.js
  ext_conf_template.txt
  ext_tables.php
Labels: enhancement

#372 [TASK] Add code coverage excludes
  Classes/XClass/Controller/FormFrontendController.php
  Classes/XClass/FormRuntime.php
  Classes/XClass/ImageService.php
  Classes/XClass/ResourceLocalDriver.php
  Classes/XClass/Routing/PageRouter.php
  Classes/XClass/Typolink/LinkResult.php
  Classes/XClass/Typolink/PageLinkBuilder.php
  Tests/Functional/ContentTypes/MenuSitemapSelectedPagesElementTest.php
  Tests/Functional/PageTypes/SchemaPageTypesTest.php
  Tests/Functional/PageTypes/StructurePageTypesTest.php
  Tests/Functional/phpunit.xml
  Tests/Unit/phpunit.xml
  composer.json
Labels: task

#373 Task/exclude more classes from code coverage analysis
  Classes/Controller/JsonViewController.php
  Classes/DataProcessing/DatabaseQueryProcessor.php
  Classes/DataProcessing/FilesProcessor.php
  Classes/DataProcessing/FlexFormProcessor.php
  Classes/DataProcessing/GalleryProcessor.php
  Classes/DataProcessing/MenuProcessor.php
  Classes/Dto/JsonViewDemand.php
  Classes/Dto/JsonViewDemandInterface.php
  Classes/Hooks/FileOrFolderLinkBuilder.php
  Classes/Hooks/PreviewUrlHook.php
  Classes/Hooks/TypolinkHook.php
  Classes/Resource/Rendering/AudioTagRenderer.php
  Classes/Resource/Rendering/VideoTagRenderer.php
  Classes/Resource/Rendering/VimeoRenderer.php
  Classes/Resource/Rendering/YouTubeRenderer.php
  Classes/Seo/XmlSitemap/PagesXmlSitemapDataProvider.php
  Classes/Seo/XmlSitemap/RecordsXmlSitemapDataProvider.php
  Classes/Seo/XmlSitemap/XmlSitemapRenderer.php
  Classes/Service/BackendTsfeService.php
  Classes/Service/BackendTsfeServiceInterface.php
  Classes/Service/JsonViewConfigurationService.php
  Classes/Service/JsonViewConfigurationServiceInterface.php
  Classes/Service/PaginationService.php
  Classes/Service/Parser/DefaultJsonParser.php
  Classes/Service/Parser/JsonParserInterface.php
  Classes/Service/Parser/PageJsonParser.php
  Classes/Utility/JsonViewMenusUtility.php
  Classes/ViewHelpers/Form/RegisterFieldViewHelper.php
  Classes/ViewHelpers/Format/Json/DecodeViewHelper.php
  Classes/ViewHelpers/Iterator/ExplodeViewHelper.php
  Classes/ViewHelpers/LoginFormViewHelper.php
Labels: task

#374 [TASK] migrate headless_domains to endpoint ?type=835
  Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
  Classes/DataProcessing/RootSiteProcessing/SiteProvider.php
  Configuration/TypoScript/Configuration/Domains.typoscript
  UPGRADE.md
Labels: task

#377 [BUGFIX] Fix undefined array key in JSON cObj
  Classes/ContentObject/JsonContentObject.php
Labels: bug
