Repository TYPO3-Headless/headless, pull requests merged in 2022-01, with the labels that each got.

#391 [BUGFIX] Resolve deprecations in v11 (for v12)
  Classes/Middleware/ShortcutAndMountPointRedirect.php
  Classes/Middleware/UserIntMiddleware.php
  Configuration/TypoScript/2.x/Helper/ParseFunc.typoscript
  Configuration/TypoScript/ContentElement/ParseFunc.typoscript
  ext_localconf.php
Labels: task

#382 [TASK] Increase code coverage
  Classes/DataProcessing/DataProcessingTrait.php
  Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
  Classes/Event/Listener/RedirectUrlAdditionalParamsListener.php
  Classes/Middleware/RedirectHandler.php
  Classes/Middleware/ShortcutAndMountPointRedirect.php
  Classes/Middleware/UserIntMiddleware.php
  Classes/Utility/FileUtility.php
  Classes/Utility/UrlUtility.php
  Tests/Unit/ContentObject/BooleanContentObjectTest.php
  Tests/Unit/ContentObject/IntegerContentObjectTest.php
  Tests/Unit/DataProcessing/DataProcessingTraitTest.php
  Tests/Unit/DataProcessing/DatabaseQueryProcessorTest.php
  Tests/Unit/DataProcessing/RootSiteProcessing/DomainSchemaTest.php
  Tests/Unit/Event/Listener/RedirectUrlAdditionalParamsListenerTest.php
  Tests/Unit/Event/RedirectUrlEventTest.php
  Tests/Unit/Hooks/HeadlessUserIntTest.php
  Tests/Unit/Json/JsonDecoderTest.php
  Tests/Unit/Middleware/ElementBodyResponseMiddlewareTest.php
  Tests/Unit/Middleware/ShortcutAndMountPointRedirectTest.php
  Tests/Unit/Middleware/UserIntMiddlewareTest.php
  Tests/Unit/Utility/FileUtilityTest.php
  Tests/Unit/Utility/UrlUtilityTest.php
Labels: task

#402 Add badges to readme
  README.md
Labels: documentation

#390 [BUGFIX] Resolve #383 - Avoid calling toArray and split properties in…
  Classes/Utility/FileUtility.php
  Tests/Unit/Utility/FileUtilityTest.php
Labels: bug
