Repository TYPO3-Headless/headless, pull requests merged in 2022-07, with the labels that each got.

#445 [BUGFIX] Fix functional tests due to typolink change
  Tests/Functional/ContentTypes/BaseContentTypeTest.php
  Tests/Functional/ContentTypes/BasicListElementTest.php
  Tests/Functional/ContentTypes/BulletsElementTest.php
  Tests/Functional/ContentTypes/HeaderElementTest.php
  Tests/Functional/ContentTypes/HtmlElementTest.php
  Tests/Functional/ContentTypes/ShortcutElementTest.php
  Tests/Functional/ContentTypes/TableElementTest.php
  Tests/Functional/ContentTypes/TextElementTest.php
  Tests/Functional/ContentTypes/TextMediaElementTest.php
  Tests/Functional/ContentTypes/TextpicElementTest.php
  Tests/Functional/Fixtures/content.xml
  Tests/Functional/Fixtures/pages.xml
Labels: bug

#444 [FEATURE] Add dependabot configuration
  .github/dependabot.yml
Labels: enhancement

#468 [FEATURE] Add workspaces preview support
  Classes/Hooks/PreviewUrlHook.php
  Classes/XClass/Controller/PreviewController.php
  Documentation/Configuration/Index.rst
  ext_localconf.php
Labels: enhancement

#467 [BUGFIX] add check if crop property is null
  Classes/DataProcessing/FilesProcessor.php
Labels: bug

#469 Update readme, add table with contents
  README.md
Labels: task
