Repository TYPO3-Headless/headless, pull requests merged in 2023-09, with the labels that each got.

#647 [DOCS] Replace JSON_CONTENT with CONTENT_JSON
  Documentation/Developer/Index.rst
Labels: documentation

#646 [BUGFIX] Set correct typoscript key for categories
  Configuration/TypoScript/Page/Categories.typoscript
Labels: bug

#651 [FEATURE] Use shared TypoScript lib for headless pages
  Configuration/TypoScript/Configuration/Domains.typoscript
  Configuration/TypoScript/Configuration/InitialDataConfiguration.typoscript
  Configuration/TypoScript/Configuration/PageConfiguration.typoscript
  Configuration/TypoScript/Page/HeadlessPage.typoscript
Labels: enhancement

#628 [FEATURE] PageTitle handler for headless
  Classes/Event/Listener/AfterCacheableContentIsGeneratedListener.php
  Configuration/Services.php
  Tests/Unit/Event/Listener/AfterCacheableContentIsGeneratedListenerTest.php
Labels: enhancement
