Repository TYPO3-Headless/headless, pull requests merged in 2023-07, with the labels that each got.

#630 [BUGFIX] Adjust Felogin with latest changes in TYPO3 core
  Classes/XClass/Controller/LoginController.php
  composer.json
  ext_emconf.php
Labels: bug

#629 [BUGFIX] Adjust felogin changes with latest TYPO3 core
  Classes/XClass/Controller/LoginController.php
  composer.json
  ext_emconf.php
Labels: bug

#631 [TASK] Migrate to TYPO3 coding standars in php-cs-fixer
  .php-cs-fixer.php
  Classes/ContentObject/JsonContentObject.php
  Classes/DataProcessing/GalleryProcessor.php
  Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
  Classes/DataProcessing/RootSitesProcessor.php
  Classes/Middleware/RedirectHandler.php
  Classes/Service/PaginationService.php
  Classes/Utility/FileUtility.php
  Classes/Utility/UrlUtility.php
  Classes/ViewHelpers/Iterator/ExplodeViewHelper.php
  Configuration/RequestMiddlewares.php
  Configuration/SiteConfiguration/Overrides/site.php
  Configuration/SiteConfiguration/Overrides/site_base_variant.php
  Tests/Functional/BaseTest.php
  Tests/Functional/PageTypes/BasePageTypesTest.php
  Tests/Unit/DataProcessing/DataProcessingTraitTest.php
  Tests/Unit/DataProcessing/RootSiteProcessing/DomainSchemaTest.php
  Tests/Unit/DataProcessing/RootSiteProcessing/TestDomainSchema.php
  Tests/Unit/DataProcessing/RootSitesProcessorTest.php
  Tests/Unit/Event/EnrichFileDataEventTest.php
  Tests/Unit/Event/Listener/RedirectUrlAdditionalParamsListenerTest.php
  Tests/Unit/Event/RedirectUrlEventTest.php
  Tests/Unit/Form/Decorator/AbstractFormDefinitionDecoratorTest.php
  Tests/Unit/Form/TranslatorTest.php
  Tests/Unit/Hooks/HeadlessUserIntTest.php
  Tests/Unit/Json/JsonDecoderTest.php
  Tests/Unit/Middleware/CookieDomainPerSiteTest.php
  Tests/Unit/Middleware/ElementBodyResponseMiddlewareTest.php
  Tests/Unit/Middleware/ShortcutAndMountPointRedirectTest.php
  Tests/Unit/Utility/FileUtilityTest.php
  Tests/Unit/Utility/UrlUtilityTest.php
  composer.json
Labels: task

#632 Bump version to 4.1.1
  ext_emconf.php
Labels: task

#633 Add templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#635 Add contributing stats
  README.md
Labels: documentation

#634 [FIX] Import custom GalleryProcessor instead of processor from fluid_…
  Configuration/Services.php
Labels: bug
